In [48]:
import warnings
warnings.filterwarnings("ignore")
from yfinance import download

In [49]:
ticker = 'klbn4.sa'

In [50]:
df = download(ticker, period="max", interval="1mo", auto_adjust=False).droplevel(1, axis=1)

[*********************100%***********************]  1 of 1 completed

In [51]:
df

Price       Adj Close     Close      High       Low      Open     Volume
Date
2008-01-01   0.547920  1.096309  1.202520  0.936093  1.175517  186257479
2008-02-01   0.514630  1.029702  1.123312  1.029702  1.101710  153146900
2008-03-01   0.521828  1.044104  1.069306  0.946894  1.044104  147539128
2008-04-01   0.584808  1.170117  1.261926  1.033303  1.038703  174480878
2008-05-01   0.578509  1.157515  1.312331  1.157515  1.170117  117099398
...               ...       ...       ...       ...       ...        ...
2025-09-01   3.328085  3.544554  3.742574  3.524752  3.663366   59051165
2025-10-01   3.337381  3.554455  3.623762  3.415841  3.564356   84067249
2025-11-01   3.309492  3.524752  3.712871  3.435643  3.564356   82341664
2025-12-01   3.581411  3.760000  3.851485  3.495049  3.534653   86779005
2026-01-01   3.700000  3.700000  3.810000  3.630000  3.760000   13055100

[217 rows x 6 columns]

In [52]:
from numpy import where
df['tipo'] = where(df['Close'] > df['Open'], 'alta', 'baixa')

In [53]:
df['sombra_superior'] = where(df['tipo'] == 'alta', 
                              df['High'] - df['Close'],
                              df['High'] - df['Open'])

In [54]:
df['sombra_inferior'] = where(df['tipo'] == 'baixa',
                              df['Close'] - df['Low'],
                              df['Open'] - df['Low'])

In [55]:
df

Price,Adj Close,Close,High,Low,Open,Volume,tipo,sombra_superior,sombra_inferior
Date,,,,,,,,,
2008-01-01,0.547920,1.096309,1.202520,0.936093,1.175517,186257479,baixa,0.027003,0.160216
2008-02-01,0.514630,1.029702,1.123312,1.029702,1.101710,153146900,baixa,0.021602,0.000000
2008-03-01,0.521828,1.044104,1.069306,0.946894,1.044104,147539128,baixa,0.025202,0.097210
2008-04-01,0.584808,1.170117,1.261926,1.033303,1.038703,174480878,alta,0.091809,0.005400
2008-05-01,0.578509,1.157515,1.312331,1.157515,1.170117,117099398,baixa,0.142214,0.000000
...,...,...,...,...,...,...,...,...,...
2025-09-01,3.328085,3.544554,3.742574,3.524752,3.663366,59051165,baixa,0.079208,0.019802
2025-10-01,3.337381,3.554455,3.623762,3.415841,3.564356,84067249,baixa,0.059406,0.138614
2025-11-01,3.309492,3.524752,3.712871,3.435643,3.564356,82341664,baixa,0.148515,0.089109
2025-12-01,3.581411,3.760000,3.851485,3.495049,3.534653,86779005,alta,0.091485,0.039604
2026-01-01,3.700000,3.700000,3.810000,3.630000,3.760000,13055100,baixa,0.050000,0.070000

In [56]:
import plotly.graph_objects as go

fig = go.Figure()

fig.add_trace(go.Candlestick(
    x=df.index,
    open=df['Open'],
    high=df['High'],
    low=df['Low'],
    close=df['Close'],
    name='Preço'
))

fig.add_trace(go.Bar(
    x=df.index,
    y=df['sombra_superior'],
    name='Sombra Superior',
    marker=dict(
        color='rgba(0, 102, 204, 0.5)'  # azul com transparência
    ),
    yaxis='y2'
))

fig.add_trace(go.Bar(
    x=df.index,
    y=df['sombra_inferior'],
    name='Sombra Inferior',
    marker=dict(
        color='rgba(0, 102, 204, 0.5)'
    ),
    yaxis='y2'
))

fig.update_layout(
    width=1600,
    height=900,
    font=dict(size=14),
    margin=dict(l=60, r=60, t=60, b=60),
    yaxis2=dict(
        overlaying='y',
        side='right',
        showgrid=False,
        title='Amplitude da Sombra'
    )
)

---

se sequência de 2 meses de alta qual a amplitude da sombra em relação ao mês anterior

In [57]:
df_a1 = df.copy()

# Se 2 dias de alta então tirar o percentual da sombra atualem relação a amplitude do dia anteior
df_a1['a1'] = where((df['tipo'].shift(1) == 'alta') & (df['tipo'] == 'alta'),  
                    df['sombra_inferior'] / (df['Close'].shift(1) - df['Open'].shift(1)),  'NaN')

df_a1.tail(30)

Price,Adj Close,Close,High,Low,Open,Volume,tipo,sombra_superior,sombra_inferior,a1
Date,,,,,,,,,,
2023-08-01,3.437289,4.131413,4.302430,3.969396,4.167416,64422880,baixa,0.135014,0.162017,NaN
2023-09-01,3.624263,4.311431,4.401440,3.960396,4.149414,42521407,alta,0.090009,0.189018,NaN
2023-10-01,3.245947,3.861386,4.401440,3.843384,4.311431,37300039,baixa,0.090009,0.018002,NaN
2023-11-01,3.465410,4.068406,4.239423,3.834383,3.861386,38632904,alta,0.171017,0.027003,NaN
2023-12-01,3.381075,3.969396,4.059405,3.681368,4.032403,78061853,baixa,0.027002,0.288028,NaN
2024-01-01,3.297290,3.843384,4.086408,3.834383,3.969396,44341332,baixa,0.117012,0.009001,NaN
2024-02-01,3.482617,4.059405,4.095409,3.699369,3.843384,42225324,alta,0.036004,0.144015,NaN
2024-03-01,3.915782,4.527452,4.554455,3.906390,4.059405,36672767,alta,0.027003,0.153015,0.7083340231354098
2024-04-01,3.565464,4.122412,4.572457,4.122412,4.536453,30385176,baixa,0.036004,0.000000,NaN
2024-05-01,3.459590,4.000000,4.336633,4.000000,4.122412,35988652,baixa,0.214221,0.000000,NaN
2024-06-01,3.694721,4.217821,4.287128,3.900990,4.019801,36470090,alta,0.069307,0.118811,NaN
2024-07-01,3.816143,4.356435,4.415841,4.089108,4.217821,26531791,alta,0.059406,0.128713,0.6500007224076402
2024-08-01,3.781451,4.316831,4.425742,4.049504,4.336633,31067095,baixa,0.089109,0.267327,NaN
2024-09-01,3.700722,4.158415,4.445544,4.099009,4.346534,21547744,baixa,0.099010,0.059406,NaN
2024-10-01,3.674288,4.128712,4.257425,3.950495,4.158415,33895600,baixa,0.099010,0.178217,NaN
2024-11-01,3.876946,4.356435,4.425742,4.000000,4.128712,31225766,alta,0.069307,0.128712,NaN
2024-12-01,4.113488,4.544554,4.712871,4.316831,4.326732,24005377,alta,0.168317,0.009901,0.04347853399194671
2025-01-01,3.988816,4.366336,4.544554,4.128712,4.544554,19408261,baixa,0.000000,0.237624,NaN
2025-02-01,3.590839,3.930693,4.405940,3.930693,4.366336,23069915,baixa,0.039604,0.000000,NaN
2025-03-01,3.391851,3.712871,4.029702,3.702970,3.930693,47576151,baixa,0.099009,0.009901,NaN
2025-04-01,3.336000,3.643564,3.762376,3.485148,3.712871,63330333,baixa,0.049505,0.158416,NaN
2025-05-01,3.326935,3.633663,3.930693,3.613861,3.643564,34447868,baixa,0.287129,0.019802,NaN
2025-06-01,3.357160,3.623762,3.693069,3.445544,3.613861,43318698,alta,0.069307,0.168317,NaN
2025-07-01,3.375505,3.643564,3.900990,3.584158,3.643564,40373841,baixa,0.257426,0.059406,NaN
2025-08-01,3.384678,3.653465,3.752475,3.524752,3.653465,43742191,baixa,0.099010,0.128713,NaN
2025-09-01,3.328085,3.544554,3.742574,3.524752,3.663366,59051165,baixa,0.079208,0.019802,NaN
2025-10-01,3.337381,3.554455,3.623762,3.415841,3.564356,84067249,baixa,0.059406,0.138614,NaN
2025-11-01,3.309492,3.524752,3.712871,3.435643,3.564356,82341664,baixa,0.148515,0.089109,NaN
2025-12-01,3.581411,3.760000,3.851485,3.495049,3.534653,86779005,alta,0.091485,0.039604,NaN
2026-01-01,3.700000,3.700000,3.810000,3.630000,3.760000,13055100,baixa,0.050000,0.070000,NaN

In [58]:
df_a1[df_a1['a1'] != "NaN"]

Price,Adj Close,Close,High,Low,Open,Volume,tipo,sombra_superior,sombra_inferior,a1
Date,,,,,,,,,,
2009-01-01,0.314896,0.630063,0.630063,0.558055,0.613861,49859456,alta,0.000000,0.055806,15.501672240802675
2009-05-01,0.291504,0.583258,0.676867,0.556255,0.556255,272981028,alta,0.093609,0.000000,0.0
2009-09-01,0.377876,0.756075,0.792079,0.651665,0.651665,269078640,alta,0.036004,0.000000,0.0
2009-12-01,0.477743,0.955895,0.981098,0.867686,0.883888,252655284,alta,0.025203,0.016202,0.12162410065504528
2010-07-01,0.466412,0.921692,0.946894,0.865886,0.900090,146521236,alta,0.025202,0.034204,2.3749529229177444
2010-11-01,0.458705,0.882088,0.900090,0.797479,0.855085,401539281,alta,0.018002,0.057606,15.997169577091782
2010-12-01,0.547638,1.053105,1.071107,0.891089,0.891089,470521271,alta,0.018002,0.000000,0.0
2011-03-01,0.617848,1.188118,1.188118,1.060306,1.107110,178812072,alta,0.000000,0.046804,0.5416635050624756
2011-11-01,0.704421,1.299729,1.310531,1.083708,1.083708,331360189,alta,0.010802,0.000000,0.0
2011-12-01,0.780523,1.440144,1.440144,1.252925,1.314131,356369354,alta,0.000000,0.061206,0.2833335632672319
2012-01-01,0.790279,1.458145,1.472547,1.386138,1.438343,250929344,alta,0.014402,0.052205,0.41428359252388436
2012-02-01,0.833208,1.537353,1.551755,1.344734,1.458145,296386464,alta,0.014402,0.113411,5.727260687130895
2012-09-01,1.062389,1.908190,1.931593,1.594959,1.643564,287938975,alta,0.023403,0.048605,3.0001177301624677
2012-10-01,1.195689,2.147614,6.709270,1.893789,1.904590,313983593,alta,4.561656,0.010801,0.04081593120958049
2012-11-01,1.206713,2.167416,2.259225,2.003600,2.151215,288202840,alta,0.091809,0.147615,0.6074099654032874
2012-12-01,1.291156,2.302430,2.329432,2.036003,2.147614,281873472,alta,0.027002,0.111611,6.889127619496115
2013-01-01,1.377973,2.457245,2.498649,2.225022,2.302430,304405663,alta,0.041404,0.077408,0.49999922999330093
2013-11-01,1.248580,2.178217,2.255625,2.019801,2.140414,274162577,alta,0.077408,0.120613,3.3499854316213282
2013-12-01,1.276006,2.207020,2.246624,2.066606,2.160216,292175218,alta,0.039604,0.093610,2.476264056459191
2014-01-01,1.284333,2.221422,2.311431,2.120612,2.207020,365524552,alta,0.090009,0.086408,1.846171871020325
2014-08-01,1.186415,2.034203,2.133213,1.953195,2.007200,24571645,alta,0.099010,0.054005,0.8571404245335674
2014-09-01,1.263390,2.133213,2.313231,1.989198,2.052205,72118999,alta,0.180018,0.063007,2.3333333333333335
2014-10-01,1.290043,2.178217,2.250225,1.980198,2.106210,25573433,alta,0.072008,0.126012,1.5555504867970287
2014-11-01,1.433974,2.421242,2.430243,2.151215,2.178217,25116813,alta,0.009001,0.027002,0.37498965296885295
2014-12-01,1.547572,2.592259,2.700270,2.313231,2.412241,4584864,alta,0.108011,0.099010,0.4074064990321989
2015-03-01,1.955959,3.276327,3.411341,2.835283,2.844284,8691120,alta,0.135014,0.009001,0.022222483834795585
2016-10-01,1.614528,2.583258,2.655265,2.421242,2.520252,4089139,alta,0.072007,0.099010,0.7333309788271027
2017-05-01,1.641556,2.574257,2.790279,2.295229,2.547254,7609231,alta,0.216022,0.252025,1.8666716111646766
2017-09-01,1.943498,3.006300,3.204320,2.718271,2.790279,5012934,alta,0.198020,0.072008,0.3076944236160918
2017-10-01,1.990049,3.078307,3.402340,2.934293,3.015301,3353654,alta,0.324033,0.081008,0.37500027592052604
2018-04-01,1.988114,3.015301,3.105310,2.898289,2.970297,2435747,alta,0.090009,0.072008,0.47059556771596983
2018-05-01,2.005919,3.042304,3.312331,2.826282,3.015301,2979470,alta,0.270027,0.189019,4.200058275058275
2019-10-01,1.958266,2.736273,2.808280,2.520252,2.637263,19886556,alta,0.072007,0.117011,3.2500264886628525
2019-11-01,2.209490,3.087308,3.195319,2.727272,2.745274,13991149,alta,0.108011,0.018002,0.181820370932243
2019-12-01,2.326357,3.195319,3.348334,3.087308,3.087308,19975996,alta,0.153015,0.000000,0.0
2020-01-01,2.701531,3.672367,3.942394,3.195319,3.195319,24475098,alta,0.270027,0.000000,0.0
2020-05-01,2.591753,3.519351,4.311431,2.925292,3.177317,70687478,alta,0.792080,0.252025,0.8484857484568521
2020-06-01,2.717696,3.690369,3.771377,3.357335,3.555355,59496816,alta,0.081008,0.198020,0.5789480654818956
2020-07-01,2.717696,3.690369,3.915391,3.555355,3.672367,36085826,alta,0.225022,0.117012,0.8666670198432249
2020-08-01,3.340776,4.536453,4.743474,3.627362,3.717371,43628070,alta,0.207021,0.090009,5.0
2020-11-01,3.307634,4.491449,4.536453,4.077407,4.266426,47635891,alta,0.045004,0.189019,6.999858732120784
2020-12-01,3.453461,4.689468,4.752475,4.230423,4.491449,36818975,alta,0.063007,0.261026,1.159997626651014
2021-01-01,3.619175,4.914491,5.499549,4.500450,4.689468,39257843,alta,0.585058,0.189018,0.9545434843333108
2021-02-01,3.897573,5.292529,5.580558,4.851485,4.959495,36231034,alta,0.288029,0.108010,0.479996100934928
2021-12-01,3.371115,4.500450,4.545454,4.005400,4.005400,11110322,alta,0.045004,0.000000,0.0
2023-05-01,3.067280,3.753375,4.068406,3.429342,3.429342,65997501,alta,0.315031,0.000000,0.0
2023-06-01,3.280027,3.942394,4.167416,3.672367,3.762376,54424881,alta,0.225022,0.090009,0.2777771646237601
2023-07-01,3.467243,4.167416,4.203420,3.735373,3.942394,49329724,alta,0.036004,0.207021,1.1500019866234024
2024-03-01,3.915782,4.527452,4.554455,3.906390,4.059405,36672767,alta,0.027003,0.153015,0.7083340231354098
2024-07-01,3.816143,4.356435,4.415841,4.089108,4.217821,26531791,alta,0.059406,0.128713,0.6500007224076402
2024-12-01,4.113488,4.544554,4.712871,4.316831,4.326732,24005377,alta,0.168317,0.009901,0.04347853399194671

In [59]:
df_a1[df_a1['a1'] != "NaN"]['a1'].astype(float)

Date
2009-01-01    15.501672
2009-05-01     0.000000
2009-09-01     0.000000
2009-12-01     0.121624
2010-07-01     2.374953
2010-11-01    15.997170
2010-12-01     0.000000
2011-03-01     0.541664
2011-11-01     0.000000
2011-12-01     0.283334
2012-01-01     0.414284
2012-02-01     5.727261
2012-09-01     3.000118
2012-10-01     0.040816
2012-11-01     0.607410
2012-12-01     6.889128
2013-01-01     0.499999
2013-11-01     3.349985
2013-12-01     2.476264
2014-01-01     1.846172
2014-08-01     0.857140
2014-09-01     2.333333
2014-10-01     1.555550
2014-11-01     0.374990
2014-12-01     0.407406
2015-03-01     0.022222
2016-10-01     0.733331
2017-05-01     1.866672
2017-09-01     0.307694
2017-10-01     0.375000
2018-04-01     0.470596
2018-05-01     4.200058
2019-10-01     3.250026
2019-11-01     0.181820
2019-12-01     0.000000
2020-01-01     0.000000
2020-05-01     0.848486
2020-06-01     0.578948
2020-07-01     0.866667
2020-08-01     5.000000
2020-11-01     6.999859
2020-12-01     1.159998
2021-01-01     0.954543
2021-02-01     0.479996
2021-12-01     0.000000
2023-05-01     0.000000
2023-06-01     0.277777
2023-07-01     1.150002
2024-03-01     0.708334
2024-07-01     0.650001
2024-12-01     0.043479
Name: a1, dtype: float64

In [60]:
df_a1[df_a1['a1'] != "NaN"]['a1'].astype(float).mean()

np.float64(1.8887408256042941)

In [61]:
len(df_a1[df_a1['a1'] != "NaN"]) / len(df)

0.2350230414746544