In [74]:
import warnings
warnings.filterwarnings("ignore")
from yfinance import download

In [75]:
ticker = 'klbn4.sa'

In [76]:
df = download(ticker, period="max", interval="1d", auto_adjust=False).droplevel(1, axis=1)

[*********************100%***********************]  1 of 1 completed

In [77]:
df

Price       Adj Close     Close      High       Low      Open    Volume
Date
2008-01-02   0.589306  1.179117  1.200720  1.161116  1.175517  20815696
2008-01-03   0.586607  1.173717  1.202520  1.159315  1.188118   4828406
2008-01-04   0.567713  1.135913  1.188118  1.117911  1.188118   8361386
2008-01-07   0.577610  1.155715  1.170117  1.126912  1.139513   5400015
2008-01-08   0.563215  1.126912  1.193519  1.126912  1.173717   8591363
...               ...       ...       ...       ...       ...       ...
2026-01-05   3.710000  3.710000  3.810000  3.710000  3.800000   3410400
2026-01-06   3.720000  3.720000  3.760000  3.710000  3.710000   1836100
2026-01-07   3.680000  3.680000  3.740000  3.670000  3.720000   2826200
2026-01-08   3.680000  3.680000  3.710000  3.630000  3.680000   2869300
2026-01-09   3.720000  3.720000  3.730000  3.680000  3.680000    599600

[4477 rows x 6 columns]

In [78]:
import pandas as pd

# Garantir datetime
df.index = pd.to_datetime(df.index)

# Primeiro dia do mês
primeiro_dia_mes = df.index.to_period('M').to_timestamp()

# Semana do mês
df['semana_mes'] = (
    ((df.index.day - 1 + primeiro_dia_mes.weekday) // 7) + 1
)

In [79]:
import numpy as np
import pandas as pd

df.index = pd.to_datetime(df.index)

primeiro_dia_mes = df.index.to_period('M').to_timestamp()
weekday_inicio = primeiro_dia_mes.weekday

df['semana_mes'] = (
    ((df.index.day - 1 + weekday_inicio) // 7) + 1
)

# Limitar no máximo a 5 semanas
df['semana_mes'] = np.where(df['semana_mes'] > 5, 5, df['semana_mes'])

In [80]:
df['semana_mes'].value_counts()

semana_mes
2    1042
3    1041
4    1025
5     943
1     426
Name: count, dtype: int64

In [81]:
df['ano_mes'] = df.index.to_period('M')
df['ano'] = df.index.year
df['mes'] = df.index.month

In [82]:
df.index = pd.to_datetime(df.index)

mapa_dias = {
    0: 'Segunda-feira',
    1: 'Terça-feira',
    2: 'Quarta-feira',
    3: 'Quinta-feira',
    4: 'Sexta-feira',
    5: 'Sábado',
    6: 'Domingo'
}

df['dia_semana'] = df.index.dayofweek.map(mapa_dias)

In [83]:
df.tail(50)

Price,Adj Close,Close,High,Low,Open,Volume,semana_mes,ano_mes,ano,mes,dia_semana
Date,,,,,,,,,,,
2025-10-27,3.309492,3.524752,3.594059,3.524752,3.584158,2650745,5,2025-10,2025,10,Segunda-feira
2025-10-28,3.383863,3.603960,3.603960,3.524752,3.534653,2231494,5,2025-10,2025,10,Terça-feira
2025-10-29,3.337381,3.554455,3.623762,3.554455,3.594059,2993842,5,2025-10,2025,10,Quarta-feira
2025-10-30,3.337381,3.554455,3.574257,3.534653,3.544554,2313304,5,2025-10,2025,10,Quinta-feira
2025-10-31,3.337381,3.554455,3.574257,3.534653,3.554455,2190589,5,2025-10,2025,10,Sexta-feira
2025-11-03,3.346678,3.564356,3.584158,3.544554,3.564356,2514395,2,2025-11,2025,11,Segunda-feira
2025-11-04,3.421048,3.643564,3.683168,3.564356,3.564356,4570149,2,2025-11,2025,11,Terça-feira
2025-11-05,3.476826,3.702970,3.712871,3.643564,3.643564,7832348,2,2025-11,2025,11,Quarta-feira
2025-11-06,3.421048,3.643564,3.712871,3.633663,3.702970,5760232,2,2025-11,2025,11,Quinta-feira
2025-11-07,3.402456,3.623762,3.663366,3.613861,3.653465,3177561,2,2025-11,2025,11,Sexta-feira
2025-11-10,3.385629,3.554455,3.613861,3.544554,3.574257,3766795,3,2025-11,2025,11,Segunda-feira
2025-11-11,3.385629,3.554455,3.574257,3.514851,3.564356,4297752,3,2025-11,2025,11,Terça-feira
2025-11-12,3.470505,3.643564,3.643564,3.534653,3.574257,3833455,3,2025-11,2025,11,Quarta-feira
2025-11-13,3.395060,3.564356,3.663366,3.554455,3.633663,3311487,3,2025-11,2025,11,Quinta-feira
2025-11-14,3.404490,3.574257,3.584158,3.554455,3.564356,2202709,3,2025-11,2025,11,Sexta-feira
2025-11-17,3.413921,3.584158,3.594059,3.534653,3.564356,2762754,4,2025-11,2025,11,Segunda-feira
2025-11-18,3.376198,3.544554,3.584158,3.544554,3.574257,2307244,4,2025-11,2025,11,Terça-feira
2025-11-19,3.357337,3.524752,3.574257,3.514851,3.544554,4671553,4,2025-11,2025,11,Quarta-feira
2025-11-21,3.338475,3.504950,3.534653,3.475247,3.524752,4017376,4,2025-11,2025,11,Sexta-feira
2025-11-24,3.281891,3.445544,3.524752,3.445544,3.504950,7870324,5,2025-11,2025,11,Segunda-feira
2025-11-25,3.329044,3.495049,3.504950,3.435643,3.465346,3759927,5,2025-11,2025,11,Terça-feira
2025-11-26,3.357337,3.524752,3.534653,3.495049,3.495049,4180289,5,2025-11,2025,11,Quarta-feira
2025-11-27,3.357337,3.524752,3.534653,3.504950,3.524752,5492582,5,2025-11,2025,11,Quinta-feira
2025-11-28,3.357337,3.524752,3.534653,3.495049,3.524752,6012732,5,2025-11,2025,11,Sexta-feira
2025-12-01,3.357337,3.524752,3.544554,3.495049,3.534653,6134639,1,2025-12,2025,12,Segunda-feira
2025-12-02,3.376198,3.544554,3.574257,3.504950,3.524752,5165645,1,2025-12,2025,12,Terça-feira
2025-12-03,3.423352,3.594059,3.594059,3.524752,3.554455,4364715,1,2025-12,2025,12,Quarta-feira
2025-12-04,3.461075,3.633663,3.633663,3.584158,3.603960,3837495,1,2025-12,2025,12,Quinta-feira
2025-12-05,3.517659,3.693069,3.732673,3.633663,3.633663,6765889,1,2025-12,2025,12,Sexta-feira
2025-12-08,3.545951,3.722772,3.732673,3.653465,3.702970,2867390,2,2025-12,2025,12,Segunda-feira
2025-12-09,3.564813,3.742574,3.851485,3.722772,3.762376,8475920,2,2025-12,2025,12,Terça-feira
2025-12-10,3.640259,3.821782,3.821782,3.732673,3.762376,3627516,2,2025-12,2025,12,Quarta-feira
2025-12-11,3.555382,3.732673,3.841584,3.722772,3.821782,5835477,2,2025-12,2025,12,Quinta-feira
2025-12-12,3.555382,3.732673,3.762376,3.693069,3.752475,4138071,2,2025-12,2025,12,Sexta-feira
2025-12-15,3.621397,3.801980,3.821782,3.702970,3.742574,5777705,3,2025-12,2025,12,Segunda-feira
2025-12-16,3.643564,3.643564,3.683168,3.584158,3.643564,5026770,3,2025-12,2025,12,Terça-feira
2025-12-17,3.653465,3.653465,3.663366,3.584158,3.643564,4198873,3,2025-12,2025,12,Quarta-feira
2025-12-18,3.740000,3.740000,3.790000,3.650000,3.680000,3722400,3,2025-12,2025,12,Quinta-feira
2025-12-19,3.670000,3.670000,3.760000,3.670000,3.750000,4628400,3,2025-12,2025,12,Sexta-feira
2025-12-22,3.730000,3.730000,3.750000,3.660000,3.690000,3426100,4,2025-12,2025,12,Segunda-feira
2025-12-23,3.740000,3.740000,3.750000,3.680000,3.730000,3110100,4,2025-12,2025,12,Terça-feira
2025-12-26,3.740000,3.740000,3.770000,3.720000,3.740000,2274000,4,2025-12,2025,12,Sexta-feira
2025-12-29,3.740000,3.740000,3.760000,3.720000,3.730000,1618900,5,2025-12,2025,12,Segunda-feira
2025-12-30,3.760000,3.760000,3.780000,3.700000,3.760000,1783000,5,2025-12,2025,12,Terça-feira
2026-01-02,3.810000,3.810000,3.810000,3.750000,3.760000,2003700,1,2026-01,2026,1,Sexta-feira
2026-01-05,3.710000,3.710000,3.810000,3.710000,3.800000,3410400,2,2026-01,2026,1,Segunda-feira
2026-01-06,3.720000,3.720000,3.760000,3.710000,3.710000,1836100,2,2026-01,2026,1,Terça-feira
2026-01-07,3.680000,3.680000,3.740000,3.670000,3.720000,2826200,2,2026-01,2026,1,Quarta-feira
2026-01-08,3.680000,3.680000,3.710000,3.630000,3.680000,2869300,2,2026-01,2026,1,Quinta-feira
2026-01-09,3.720000,3.720000,3.730000,3.680000,3.680000,599600,2,2026-01,2026,1,Sexta-feira

In [84]:
df.loc[df['semana_mes'] == 5]

Price,Adj Close,Close,High,Low,Open,Volume,semana_mes,ano_mes,ano,mes,dia_semana
Date,,,,,,,,,,,
2008-01-28,0.553318,1.107110,1.107110,1.053105,1.060306,5383350,5,2008-01,2008,1,Segunda-feira
2008-01-29,0.556916,1.114311,1.116111,1.080108,1.114311,4030708,5,2008-01,2008,1,Terça-feira
2008-01-30,0.553318,1.107110,1.119711,1.080108,1.108910,4297903,5,2008-01,2008,1,Quarta-feira
2008-01-31,0.547920,1.096309,1.116111,1.065706,1.098109,5801086,5,2008-01,2008,1,Quinta-feira
2008-02-25,0.545221,1.090909,1.090909,1.071107,1.080108,7522025,5,2008-02,2008,2,Segunda-feira
...,...,...,...,...,...,...,...,...,...,...,...
2025-11-26,3.357337,3.524752,3.534653,3.495049,3.495049,4180289,5,2025-11,2025,11,Quarta-feira
2025-11-27,3.357337,3.524752,3.534653,3.504950,3.524752,5492582,5,2025-11,2025,11,Quinta-feira
2025-11-28,3.357337,3.524752,3.534653,3.495049,3.524752,6012732,5,2025-11,2025,11,Sexta-feira
2025-12-29,3.740000,3.740000,3.760000,3.720000,3.730000,1618900,5,2025-12,2025,12,Segunda-feira
2025-12-30,3.760000,3.760000,3.780000,3.700000,3.760000,1783000,5,2025-12,2025,12,Terça-feira

In [85]:
df['ret'] = df['Close'].pct_change(1)
df.tail(3)

Price,Adj Close,Close,High,Low,Open,Volume,semana_mes,ano_mes,ano,mes,dia_semana,ret
Date,,,,,,,,,,,,
2026-01-07,3.68,3.68,3.74,3.67,3.72,2826200,2,2026-01,2026,1,Quarta-feira,-0.010753
2026-01-08,3.68,3.68,3.71,3.63,3.68,2869300,2,2026-01,2026,1,Quinta-feira,0.000000
2026-01-09,3.72,3.72,3.73,3.68,3.68,599600,2,2026-01,2026,1,Sexta-feira,0.010870

In [86]:
df['ret_acum_semana'] = (
    df
    .sort_index()
    .groupby(['ano_mes', 'semana_mes'])['ret']
    .cumsum()
)

In [87]:
df.tail(20)

Price,Adj Close,Close,High,Low,Open,Volume,semana_mes,ano_mes,ano,mes,dia_semana,ret,ret_acum_semana
Date,,,,,,,,,,,,,
2025-12-09,3.564813,3.742574,3.851485,3.722772,3.762376,8475920,2,2025-12,2025,12,Terça-feira,0.005319,0.013362
2025-12-10,3.640259,3.821782,3.821782,3.732673,3.762376,3627516,2,2025-12,2025,12,Quarta-feira,0.021164,0.034526
2025-12-11,3.555382,3.732673,3.841584,3.722772,3.821782,5835477,2,2025-12,2025,12,Quinta-feira,-0.023316,0.011210
2025-12-12,3.555382,3.732673,3.762376,3.693069,3.752475,4138071,2,2025-12,2025,12,Sexta-feira,0.000000,0.011210
2025-12-15,3.621397,3.801980,3.821782,3.702970,3.742574,5777705,3,2025-12,2025,12,Segunda-feira,0.018568,0.018568
2025-12-16,3.643564,3.643564,3.683168,3.584158,3.643564,5026770,3,2025-12,2025,12,Terça-feira,-0.041667,-0.023099
2025-12-17,3.653465,3.653465,3.663366,3.584158,3.643564,4198873,3,2025-12,2025,12,Quarta-feira,0.002717,-0.020382
2025-12-18,3.740000,3.740000,3.790000,3.650000,3.680000,3722400,3,2025-12,2025,12,Quinta-feira,0.023686,0.003304
2025-12-19,3.670000,3.670000,3.760000,3.670000,3.750000,4628400,3,2025-12,2025,12,Sexta-feira,-0.018717,-0.015412
2025-12-22,3.730000,3.730000,3.750000,3.660000,3.690000,3426100,4,2025-12,2025,12,Segunda-feira,0.016349,0.016349
2025-12-23,3.740000,3.740000,3.750000,3.680000,3.730000,3110100,4,2025-12,2025,12,Terça-feira,0.002681,0.019030
2025-12-26,3.740000,3.740000,3.770000,3.720000,3.740000,2274000,4,2025-12,2025,12,Sexta-feira,0.000000,0.019030
2025-12-29,3.740000,3.740000,3.760000,3.720000,3.730000,1618900,5,2025-12,2025,12,Segunda-feira,0.000000,0.000000
2025-12-30,3.760000,3.760000,3.780000,3.700000,3.760000,1783000,5,2025-12,2025,12,Terça-feira,0.005348,0.005348
2026-01-02,3.810000,3.810000,3.810000,3.750000,3.760000,2003700,1,2026-01,2026,1,Sexta-feira,0.013298,0.013298
2026-01-05,3.710000,3.710000,3.810000,3.710000,3.800000,3410400,2,2026-01,2026,1,Segunda-feira,-0.026247,-0.026247
2026-01-06,3.720000,3.720000,3.760000,3.710000,3.710000,1836100,2,2026-01,2026,1,Terça-feira,0.002695,-0.023551
2026-01-07,3.680000,3.680000,3.740000,3.670000,3.720000,2826200,2,2026-01,2026,1,Quarta-feira,-0.010753,-0.034304
2026-01-08,3.680000,3.680000,3.710000,3.630000,3.680000,2869300,2,2026-01,2026,1,Quinta-feira,0.000000,-0.034304
2026-01-09,3.720000,3.720000,3.730000,3.680000,3.680000,599600,2,2026-01,2026,1,Sexta-feira,0.010870,-0.023434

In [90]:
ret_ultimo = (
    df
    .groupby(['ano', 'mes', 'semana_mes'])['ret_acum_semana']
    .last()
    .reset_index()
)

In [93]:
ret_ultimo

       ano  mes  semana_mes  ret_acum_semana
0     2008    1           1        -0.036788
1     2008    1           2        -0.071120
2     2008    1           3        -0.016319
3     2008    1           4         0.040386
4     2008    1           5         0.022165
...    ...  ...         ...              ...
1006  2025   12           3        -0.015412
1007  2025   12           4         0.019030
1008  2025   12           5         0.005348
1009  2026    1           1         0.013298
1010  2026    1           2        -0.023434

[1011 rows x 4 columns]

In [ ]:
for i in range(1, 6):
    perc_pos = len(ret_ultimo.loc[(ret_ultimo['semana_mes'] == i) & (ret_ultimo['ret_acum_semana'] > 0)]) / len(ret_ultimo.loc[ret_ultimo['semana_mes'] == i])
    print(f'{i} {perc_pos:.2%}')

1 49.33%
2 47.93%
3 56.48%
4 49.07%
5 55.66%

In [107]:
for i in range(1, 6):      
    perc_neg = len(ret_ultimo.loc[(ret_ultimo['semana_mes'] == i) & (ret_ultimo['ret_acum_semana'] < 0)]) / len(ret_ultimo.loc[ret_ultimo['semana_mes'] == i])
    print(f'{i} {perc_neg:.2%}')

1 45.33%
2 49.77%
3 41.20%
4 49.54%
5 42.92%

In [95]:
import plotly.express as px

heat = ret_ultimo.pivot_table(
    values='ret_acum_semana',
    index='ano',
    columns='semana_mes',
    aggfunc='mean'
)

fig = px.imshow(
    heat,
    aspect='auto',
    color_continuous_scale='RdBu',
    title='Heatmap – Retorno médio por semana do mês'
)

fig.update_layout(
    width=1000,
    height=700
)

fig.show()

In [97]:
fig = px.box(
    ret_ultimo,
    x='semana_mes',
    y='ret_acum_semana',
    title='Distribuição do retorno acumulado por semana do mês'
)

fig.update_layout(
    width=1000,
    height=600
)

fig.show()