In [9]:
import warnings
warnings.filterwarnings("ignore")

In [1]:
from yfinance import download
df_data = download("vale3.sa", period="10y", interval="1d", auto_adjust=False).droplevel(1, axis=1)

[*********************100%***********************]  1 of 1 completed

In [2]:
df_data

Price       Adj Close      Close       High        Low       Open    Volume
Date
2015-12-28   6.249380  12.640000  13.170000  12.560000  13.000000   3095800
2015-12-29   6.288935  12.720000  12.810000  12.300000  12.610000   2890100
2015-12-30   6.442203  13.030000  13.140000  12.630000  12.880000   5226600
2016-01-04   6.274104  12.690000  12.980000  12.480000  12.490000   4587900
2016-01-05   6.190052  12.520000  12.840000  12.410000  12.670000   2693500
...               ...        ...        ...        ...        ...       ...
2025-12-18  70.349998  70.349998  71.120003  70.309998  70.599998  18430200
2025-12-19  70.849998  70.849998  70.930000  70.379997  70.500000  37147100
2025-12-22  72.919998  72.919998  73.370003  70.809998  71.029999  27853000
2025-12-23  72.900002  72.900002  73.529999  72.580002  73.230003  17140900
2025-12-26  73.120003  73.120003  73.349998  72.620003  72.860001  16368800

[2492 rows x 6 columns]

In [3]:
ret_mensal_1 = df_data.resample('M').agg(
    open_mes=('Open', 'first'),
    close_mes=('Close', 'last')
)

ret_mensal_1['retorno_mensal'] = (
    ret_mensal_1['close_mes'] - ret_mensal_1['open_mes']
)

C:\Users\rian\AppData\Local\Temp\ipykernel_7204\2089439763.py:1: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  ret_mensal_1 = df_data.resample('M').agg(

In [5]:
ret_mensal_1.tail(30)

             open_mes  close_mes  retorno_mensal
Date
2023-07-31  64.709999  69.160004        4.450005
2023-08-31  68.769997  65.080002       -3.689995
2023-09-30  66.690002  67.580002        0.889999
2023-10-31  67.580002  69.000000        1.419998
2023-11-30  69.260002  73.849998        4.589996
2023-12-31  74.730003  77.199997        2.469994
2024-01-31  77.599998  67.760002       -9.839996
2024-02-29  67.870003  66.989998       -0.880005
2024-03-31  66.889999  60.830002       -6.059998
2024-04-30  61.599998  63.290001        1.690002
2024-05-31  63.700001  63.200001       -0.500000
2024-06-30  62.840000  62.220001       -0.619999
2024-07-31  62.709999  61.630001       -1.079998
2024-08-31  61.849998  59.580002       -2.269997
2024-09-30  58.820000  63.509998        4.689999
2024-10-31  63.500000  62.060001       -1.439999
2024-11-30  62.139999  58.779999       -3.360001
2024-12-31  58.849998  54.549999       -4.299999
2025-01-31  54.709999  54.169998       -0.540001
2025-02-28  53.730000  55.150002        1.420002
2025-03-31  56.150002  56.700001        0.549999
2025-04-30  57.099998  52.860001       -4.239998
2025-05-31  53.259998  52.099998       -1.160000
2025-06-30  52.580002  52.650002        0.070000
2025-07-31  52.599998  53.459999        0.860001
2025-08-31  54.240002  55.560001        1.320000
2025-09-30  55.139999  57.580002        2.440002
2025-10-31  57.759998  65.260002        7.500004
2025-11-30  65.099998  67.400002        2.300003
2025-12-31  67.800003  73.120003        5.320000

In [10]:
ret_mensal_2 = df_data['Close'].pct_change(1).resample('M').sum()

In [11]:
ret_mensal_2

Date
2015-12-31    0.030700
2016-01-31   -0.275388
2016-02-29    0.230882
2016-03-31    0.292315
2016-04-30    0.292587
                ...
2025-08-31    0.039958
2025-09-30    0.036134
2025-10-31    0.126644
2025-11-30    0.032936
2025-12-31    0.084442
Freq: ME, Name: Close, Length: 121, dtype: float64